---

 - name: Install RPM for Remi repo
   yum:
    name: "{{ remi_url }}"
    state: installed

 - name: Install common PHP 71 and commin libs
   yum:
    name:
        - php
        - php-common
        - php-cli
        - php-pear
        - php-pdo
        - php-mysqlnd
        - php-gd
        - php-mbstring
        - php-mcrypt
        - php-xml
    enablerepo: remi, remi-php71
   notify:
    - Restart Apache