---
- name: Debug
  hosts: all
  tasks:
    - name: Dump variables
      debug:
        msg: "Memcached server: {{ groups['memcache'][0] }}"
  tags:
    - debug
  
- name: Install Docker on hosts
  hosts: card_stock
  become: yes
  vars:
    - username: card-stock
  roles:
    - docker
  tags:
    - dependencies 

- name: Deploy Traefik container for reverse proxy
  hosts: card_stock
  become: yes
  roles:
    - traefik
  tags: 
    - traefik

- name: Deply card-stock application
  hosts: card_stock
  become: yes
  tasks:
    - name: Include vaulted vars
      include_vars:
        file:  secrets/card_stock/vars.yml
      tags:
        - deploy_card_stock_container
        - deploy_mysql_container

    # - name: Create internal network for application
    #   docker_network:
    #     name: internal
    #     internal: yes
    #   tags:
    #     - deploy_mysql_container

    # - name: Deploy MySQL Database
    #   docker_container:
    #     name: mysql
    #     image: "mysql:8.0.19"
    #     state: absent
    #     restart_policy: always
    #     ports:
    #       - "3306:3306"
    #     capabilities:
    #       - SYS_NICE
    #     env:
    #       MYSQL_USER: "{{ mysql_user }}"
    #       MYSQL_PASSWORD: "{{ mysql_password }}"
    #       MYSQL_DATABASE: "{{ mysql_database }}"
    #       MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    #     networks_cli_compatible: yes
    #     networks:
    #       - name: internal
    #   tags:
    #     - deploy_mysql_container
    
    - name: Create directories for application
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/card-stock/logs/
        - /opt/card-stock/data/

    - name: Deploy card-stock application
      docker_container:
        name: card-stock
        image: "us.gcr.io/tools96810d6b/card-stock:{{ version }}"
        state: started
        restart_policy: always
        volumes:
          - "/opt/card-stock/logs/:/app/logs/"
          - "/opt/card-stock/data/:/app/data/"
        env:
          FLASK_CONFIG: "production"
          GOOGLE_CLIENT_ID: "{{ google_client_id }}"
          GOOGLE_CLIENT_SECRET: "{{ google_secret_id }}"
          EBAY_APP_ID: "{{ ebay_app_id }}"
          SQLALCHEMY_DATABASE_URI: "{{ sqlalchemy_database_uri }}"
          REDIRECT_URI: "https://{{ hostname }}/callback"
          SMTP_PASSWORD: "{{ smtp_password }}"
          MEMCACHED_SERVERS: "{{ groups['memcache'][0] }}"
        labels:
          traefik.enable: "true"
          traefik.http.routers.card-stock.rule: "Host(`{{ hostname }}`)"
          traefik.http.routers.card-stock.tls: "true"
          traefik.http.routers.card-stock.tls.certresolver: "le"
          traefik.docker.network: "traefik"    
        networks:
          - name: traefik
      tags:
        - deploy_card_stock_container

  tags:
    - deploy_app_container

- name: Install memcached  on hosts
  hosts: memcache
  become: yes
  roles:
    - memcache
  tags:
    - deploy_memcached 