---

- name: clean-up existing certbot packages
  ansible.builtin.package:
    name: certbot
    state: absent

- name: install certbot with snapd
  community.general.snap:
    name: certbot
    classic: yes

- name: symlink /snap/bin/certbot to /usr/bin/certbot
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: install python packages for cloudflare-certbot-dns
  ansible.builtin.package:
    name:
    - python2-cloudflare 
    - python2-certbot-dns-cloudflare
    state: present