---

- name: Include secret vars
  include_vars: ../../secrets/cloudflare/vars.yml

- include_tasks: snap_rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_tasks: install.yml

- include_tasks: configure.yml

# - include_tasks: post.yml