---
  - name: Install Jenkins from repo
    package:
      name: 
      - jenkins
      - java-1.8.0-openjdk-devel
      - git
      state: present
  
  - name:  Force systemd to reread configs
    systemd:
      daemon_reload: yes