---
 - name: "Create LetsEncrypt directores in /etc/letsencrypt"
   file:
     path: "/etc/letsencrypt{{ item }}"
     state: directory
     owner: root
     group: root
     mode: u=rwx,g=x,o=x
   with_items:
    - account
    - certs
    - csrs
    - keys

 - name: